source 'http://rubygems.org'

gem 'rails', '3.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'

#gem 'mocha'

#gem 'formtastic', "1.0.0.beta", :git => "git://github.com/justinfrench/formtastic.git", :branch => "rails3"

gem 'shoulda', '>= 2.11.3'
gem 'factory_girl_rails', '>= 1.0.0'
gem 'nokogiri', '>= 1.4.3.1'

gem 'capybara', ">= 0.3.9"
gem 'database_cleaner', ">= 0.5.2"
gem 'cucumber-rails', '>= 0.3.2'
gem 'cucumber', '>= 0.8.5'
gem 'launchy', '>= 0.3.7'

# universal flash messages
gem 'universal_flash_messages'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri', '1.4.1'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
